에러 처리 <sub>(`try…catch`)</sub>
====

##### 다양한 에러 원인
- 실수
- 예상치 못한 사용자 입력
- 잘못된 서버 응답
- 기타 등등

##### 에러 결과
- 스크립트 즉시 중단
- 콘솔 내 에러 출력

### `try…catch` 문법

##### 기능
- 스크립트 중단 방지
- 에러 진행 방지
  - 더 합당한 작업 실행

##### 주요 구성 블록 <sub>(2가지)</sub>
- a. `try{…}`
- b. `catch(…){…}`
```javascript
try {
  …코드 실행…
} catch(e) {
  …에러 처리…
}
```

#### 동작 알고리즘

##### 1. 코드 실행
- `try{…}` <sub>(블록)</sub>

##### 2. 에러 無
- `try{…}` <sub>(블록)</sub> 내 코드 실행 완료
- `catch(…){…}` <sub>(블록)</sub> 미실행

##### 3. 에러 有
- `try{…}` <sub>(블록)</sub> 내 코드 실행 중단
- `catch(e){…}` <sub>(블록)</sub> 실행 <sub>(제어 흐름 이동)</sub>
  - `e` <sub>(변수)</sub>
    - 에러 <sub>(정보)</sub> 객체 포함

![try-catch-flow](../../images/01/10/01/try-catch-flow.svg)

##### 에러 無 예시
```javascript
try {
  alert('try 블록 시작'); // 정상 실행

  // …코드 정상 실행…

  alert('try 블록 끝');  // 정상 실행

//catch 블록 무시
} catch(e) {
  alert('에러 無 → catch 무시');
}
```

##### 에러 有 예시
```javascript
try {
  alert('try 블록 시작'); // 정상 실행

  lalala;              // 에러 (미정의 변수)

  alert('try 블록 끝');  // 미실행 (도달 X)

// 에러 시 catch 블록 즉시 실행
} catch(e) {
  alert('에러');
}
```

<br />

<img src="../../images/commons/icons/triangle-exclamation-solid.svg" /> **`try…catch` 동작 대상 <sub>(런타임 에러)</sub>**

##### 실행 가능 <sub>(유효)</sub> 코드 <sub>(문법 문제 無)</sub> 대상 동작
- 실행 불가능 <sub>(무효)</sub> 코드 대상 동작 X
  - 부적절한 문법
```javascript
try {
  {{{{{{{{{{{{ // 잘못된 문법
} catch(e) {
  alert("무효 코드 → JS 엔진 코드 이해 불가능");
}
```

#### 에러 구분

##### 파싱 에러
- 코드 읽기 중 발생
- 엔진 해당 코드 이해 불가능
  - 코드 내 복구 불가능

##### 런타임 에러 <sub>(≒ 예외)</sub>
- 코드 실행 중 발생
- `try…catch` 동작 대상

<br />

<img src="../../images/commons/icons/triangle-exclamation-solid.svg" /> **`try…catch` 동기 동작**

##### 예약 실행 코드 <sub>(`setTimeout` 등)</sub> 내 에러 처리 불가능
- `try…catch` 종료 후 예약 함수 실행
```javascript
try {
  setTimeout(function() {
    noSuchVariable; // 스크립트 중단
  }, 1000);
} catch(e) {
  alert( "작동 중단" );
}
```
- 예약 함수 내 `try…catch` 구현 필요
```javascript
setTimeout(function() {
  try {
    noSuchVariable; // try…catch 내 에러 처리
  } catch {
    alert( "에러 처리 성공" );
  }
}, 1000);
```

<br />

### 에러 객체

##### 에러 상세 정보 저장
- 에러 시 생성 후
  - `catch(…){…}` <sub>(블록)</sub> 인수 전달
```javascript
try {
  …
} catch(e) { // e (에러 객체)
  …          // - 인수명 변경 가능
}
```

##### 주요 프로퍼티
- `name` <sub>(문자열)</sub>
  - 에러명 <sub>(`'ReferenceError'` 등)</sub>
- `message` <sub>(문자열)</sub>
  - 에러 상세 정보

##### 이 외 프로퍼티 <sub>(非표준 · 대다수 호스트 환경 지원)</sub>
- `stack` <sub>(문자열 · 사용 빈도 多)</sub>
  - 현재 호출 스택 <sub>(에러 유발 중첩 호출 순서)</sub>
  - 디버깅 용도
```javascript
try {
  lalala; // 에러 (변수 미정의)
} catch(e) {
  e.name;    // ReferenceError
  e.message; // lalala is not defined
  e.stack;   // ReferenceError: lalala is not defined at … (호출 스택)

  // 에러 전체 표시 ("name: message" 형태)
  e;         // ReferenceError: lalala is not defined
}
```

### 선택적 `catch` <sub>(문)</sub> 바인딩

<img src="../../images/commons/icons/triangle-exclamation-solid.svg" /> **최근 명세서 추가**

##### 구식 브라우저
- 폴리필 필요

<br />

##### `catch` <sub>(문)</sub> 인수 <sub>(에러 객체)</sub> 생략 가능
- 에러 상세 정보 불필요 시 생략
```javascript
try {
  …
} catch { // 인수 (에러 객체) 생략
  …
}
```

### `try…catch` 사용

##### [`JSON.parse`](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) <sub>(메서드)</sub>
- JSON <sub>(인코딩 값)</sub> → 값 변환
- 주요 용도
  - 네트워크 <sub>(서버 등)</sub> 수신 데이터 디코딩
```javascript
// 네트워크 (서버 등) 수신 데이터 (문자열)
let json = '{"name":"John", "age": 30}';

// JSON (인코딩 문자열) → 객체 변환
let user = JSON.parse(json);
/*  user = {
  name: "John",
  age: 30
}
 */
```

##### 부적절한 JSON 형식
- `JSON.parse` <sub>(메서드)</sub> 실행 시 에러
  - 미처리 시 스크립트 중단 발생
  - `try…catch` 사용한 처리 필요
```javascript
// 부적절한 JSON 형식
let json = "{bad json}";

try {
  let user = JSON.parse(json); // 에러

  user.name; // 미실행 (도달 X)

// 에러 시 catch(문) 제어 흐름 이동
} catch(e) {
  "데이터에 에러가 있어 재요청을 시도합니다.";
  e.name;
  e.message;
}
```

##### `catch(…){…}` <sub>(블록)</sub>
- 에러 후 구체적인 동작 실행 가능
  - 새 네트워크 요청 전송
  - 사용자 대안 제안
  - 로깅 장치 에러 정보 전송
  - 기타 등등

### 직접 에러 생성 후 던지기

##### 문법 정상 · 불완전 데이터
- `JSON.parse` <sub>(메서드)</sub> 정상 실행 <sub>(문법 정상)</sub>
  - `name` <sub>(프로퍼티)</sub> 無
    - 추후 에러 유발
```javascript
// 불완전 데이터
// - name (프로퍼티) 無
let json = '{"age": 30}';

try {

  // JSON → 객체 변환 시 에러 X (문법 정상)
  let user = JSON.parse(json);

  // name (프로퍼티) 無 (추후 에러 유발)
  user.name; // "" (빈 문자열)

} catch(e) {
  "실행되지 않습니다.";
}
```

#### `throw` <sub>(연산자)</sub>

##### 에러 생성
```javascript
throw <error object>
```

##### 에러 객체
- 모든 값 사용 가능 <sub>(원시형 자료 등)</sub>
- 객체 <sub>(표준 프로퍼티 구현)</sub> 권장 <sub>(내장 에러 객체 호환)</sub>
  - `name` <sub>(문자열)</sub>
    - 에러명
  - `message` <sub>(문자열)</sub>
    - 에러 상세 정보

##### 표준 에러 객체 생성자
- `Error`
- `SyntaxError`
- `ReferenceError`
- `TypeError`
- 기타 등
```javascript
let e1 = new Error(message);
let e2 = new SyntaxError(message);
let e3 = new ReferenceError(message);
…
```

##### 내장 에러 객체 <sub>(내장 생성자 사용)</sub>
- `name` <sub>(프로퍼티)</sub>
  - 내장 생성자명
- `message` <sub>(프로퍼티)</sub>
  - 내장 생성자 인수
```javascript
let e = new Error("이상한 일이 발생했습니다. o_O");

e.name;    // Error
e.message; // 이상한 일이 발생했습니다. o_O
```

##### `SyntaxError` <sub>(에러)</sub>
- `JSON.parse` <sub>(메서드)</sub> 실행 후
  - 부적절한 JSON 형식 변환 시 발생
```javascript
try {
  JSON.parse("{잘못된 형식의 json o_O}");
} catch(e) {
  e.name;    // SyntaxError
  e.message; // Unexpected token b in JSON at position 2
}
```

##### 문법 정상 · 불완전 데이터 → 에러 간주
- `JSON.parse` <sub>(메서드)</sub> 실행 시
  1. 에러 생성 후 던지기 <sub>(`throw` 연산자 )</sub>
  2. 에러 처리 <sub>(`try…catch`)</sub>
```javascript
// 불완전 데이터
// - name (프로퍼티) 無
let json = '{"age": 30}';

try {

  // JSON → 객체 변환 시 에러 X (문법 정상)
  let user = JSON.parse(json);

  // name (프로퍼티) 유무 여부 확인
  if (!user.name) {

    /* throw (연산자)
     SyntaxError (에러 객체) 생성
     - 생성자 인수 → message (에러 객체 내 프로퍼티) 할당
       - JS 자체 에러 생성 방식 동일
     제어 흐름 이동
     - try (문) 즉시 실행 중단
     - catch (문) 실행
     */
    throw new SyntaxError("불완전 데이터 (이름 없음)");
  }

  user.name; // 미실행 (도달 X)

// catch(…){…} (블록) 내 모든 에러 처리
} catch(e) {
  e; // SyntaxError: 불완전 데이터 (이름 없음)
}
```

### 에러 다시 던지기

##### 다양한 에러 발생 가능
- 미정의 변수 사용
- 기타 등등
```javascript
// 불완전 데이터
let json = '{"age": 30}';

try {

  // let 미선언 (에러)
  user = JSON.parse(json);

  if (!user.name) {
    throw new SyntaxError("불완전 데이터 (이름 없음)");
  }

  user.name;
} catch(e) {
  e; // ReferenceError: user is not defined
     // SyntaxError: … X
}
```

##### `catch` <sub>(절)</sub>
- `try{…}` <sub>(블록)</sub> 내 모든 에러 처리
- 다양한 에러 <sub>(미정의 변수 등)</sub> 가능
  - 모든 에러 동일 처리 시 디버깅 난이도 ↑

#### 다시 던지기

##### `catch` <sub>(절)</sub>
- 담당 에러만 처리
  - 이 외 에러 '다시 던지기'

##### 과정
1. `catch` <sub>(문)</sub>
   - 모든 에러 받기
2. `catch(e){…}` <sub>(블록)</sub>
   - `e` <sub>(에러 객체)</sub> 분석
3. 처리 불가능 에러 다시 던지기
   - `throw e`

<br />

##### 에러 종류 확인
- 보통 `instanceof` <sub>(연산자)</sub> 사용
- 에러 클래스명 사용
  - `name` <sub>(프로퍼티)</sub>
  - `constructor.name` <sub>(프로퍼티)</sub>
```javascript
try {
  user = {…};
} catch(e) {
  if (e instanceof SyntaxError) {
    /* …문법 에러 처리… */
  } else if (e.name == 'ReferenceError') {
    /* …미정의 변수 접근 에러 처리… */
  }
}
```

##### `SyntaxError` 외 에러 다시 던지기
```javascript
// 불완전 데이터
let json = '{"age": 30}';

try {
  let user = JSON.parse(json);

  if (!user.name) {
    throw new SyntaxError("불완전 데이터 (이름 없음)");
  }

  blabla(); // 에러

  user.name;
} catch(e) {

  // SyntaxError 처리
  if (e instanceof SyntaxError) {
    e.message;

  // 이 외 에러 다시 던지기
  } else {
    throw e;
  }
}
```

##### 외부 `try…catch`
- 다시 던져진 에러 잡음
- 부재 시 스크립트 중단

##### 외부 `try…catch` 내 다시 던져진 에러 처리
```javascript
function readData() {
  let json = '{"age": 30}';

  try {
    let user = JSON.parse(json);

    if (!user.name) {
      throw new SyntaxError("불완전 데이터 (이름 없음)");
    }

    blabla(); // 에러
  } catch(e) {

    // SyntaxError 외 에러 다시 던지기
    if (!(e instanceof SyntaxError)) {
      throw e;
    }
  }
}

// 외부 try…catch
try {
  readData();
} catch(e) {
  e; // 다시 던져진 에러 잡음
}
```

### `try…catch…finally`

##### `finally` <sub>(절)</sub> 실행 시점
- 에러 無
  - `try{…}` <sub>(블록)</sub> 실행 후
- 에러 有
  - `catch(…){…}` <sub>(블록)</sub> 실행 후

##### `try…catch` → `try…catch…finally` <sub>(확장)</sub>
```javascript
try {
   …코드 실행…
} catch(e) {
   …에러 처리…
} finally {
   …항상 실행…
}
```

##### 코드 실행 경로
- 에러 有 <sub>(yes)</sub>
  - `try` → `catch` → `finally`
- 에러 無 <sub>(no)</sub>
    - `try` → `finally`
```javascript
try {
  'try 블록 시작';
  if (confirm('에러를 만드시겠습니까?')) {
    이상한_코드(); // 에러
  }
} catch(e) {
  'catch';   // 에러 처리
} finally {
  'finally'; // 항상 실행
}
```

##### 주요 용도
- 실행 완료 <sub>(실행 결과 무관)</sub>

##### `fib(n)` <sub>(피보나치 함수)</sub> 연산 시간 측정
- 함수 실행 전 · 후 측정 시작 · 종료
- 함수 실행 도중 에러 경우
  - 非정수 · 음수 입력 등
- `finally` <sub>(절)</sub>
  - 항상 연산 시간 측정 가능 <sub>(결과 무관)</sub>
    - 정상 실행 시
    - 에러 시
```javascript
function fib(n) {
  if (n < 0 || Math.trunc(n) != n) {
    throw new Error("음수나 정수가 아닌 값은 처리할 수 없습니다.");
  }
  return n <= 1 ? n : fib(n - 1) + fib(n - 2);
}

let num = +prompt("양의 정수를 입력해주세요.", 35)
let diff, result;
let start = Date.now();

try {
  result = fib(num);
} catch(e) {
  result = 0;
} finally {

  // 항상 시간 측정 (결과 무관)
  diff = Date.now() - start;
}

result || "에러";
`연산 시간: ${diff}ms`;
```
- `35`
  1. `try{…}` <sub>(블록)</sub> 실행
  2. `finally{…}` <sub>(블록)</sub> 실행
- `-1` <sub>(에러)</sub>
  1. `catch(…){…}` <sub>(블록)</sub> 실행
  2. `finally{…}` <sub>(블록)</sub> 실행
     - `0ms` <sub>(연산 시간)</sub>
- `return` · `throw` <sub>(문)</sub> 도달 시 함수 종료
  - `finally` <sub>(절)</sub> 모두 처리 가능

<br />

<img src="../../images/commons/icons/circle-exclamation-solid.svg" /> **`try…catch…finally` 내 변수 == 지역 변수**

##### `try…catch…finally{…}` <sub>(블록)</sub> 내 선언 변수
- 지역 변수
  - `{…}` <sub>(블록)</sub> 내에서만 유효

<br />

<img src="../../images/commons/icons/circle-exclamation-solid.svg" /> **`finally` <sub>(절)</sub> · `return` <sub>(문)</sub>**

##### `try…catch` <sub>(절)</sub> 종료 시 `finally` <sub>(절)</sub> 실행
- `try{…}` <sub>(블록)</sub>
  - 코드 정상 실행
  - `return` <sub>(지시자)</sub> 사용 <sub>(명시적 종료)</sub>
- `catch(…){…}` <sub>(블록)</sub>
  - 에러 처리
  - 에러 다시 던지기
- 기타 등등

##### `try{…}` <sub>(블록)</sub> 내 `return` <sub>(지시자)</sub> 사용 시
- 값 외부 반환 전 `finally` <sub>(절)</sub> 실행
```javascript
function func() {
  try {
    return 1;
  } catch(e) {
    …
  } finally {
    'finally';
  }
}

// finally (절) 실행 후 값 할당
let result = func(); // finally
```

<br />

<img src="../../images/commons/icons/circle-exclamation-solid.svg" /> **`try…finally 구문`**

##### `catch` <sub>(절)</sub> 생략
- 에러 처리 동작 無
  - `try` <sub>(절)</sub> 내 에러 시 외부 전파
- 프로세스 종료 확인
  - 실행 흐름 이탈 전 `finally` <sub>(절)</sub> 실행

```javascript
function func() {
  try {
    …작업…
  } finally {
    …작업 마무리…
  }
}
```

### 전역 `catch` <sub>(문)</sub>

<img src="../../images/commons/icons/triangle-exclamation-solid.svg" /> **호스트 환경 확인 필요**

- 코어 JS X

<br />

##### `try…catch` 외부 치명적인 에러 시 스크립트 중단
- 대처 방법
  - 에러 내역 기록
  - 사용자 알림
  - 기타 등등
- 명세서
  - 대응 방법 내용 無
- 대다수 JS 호스트 환경
  - 자체 에러 처리 기능 제공

#### [`window.onerror`](https://developer.mozilla.org/ko/docs/Web/API/GlobalEventHandlers/onerror) <sub>(브라우저 전역 핸들러)</sub>

##### 치명적인 에러 시 실행
```javascript
window.onerror = function(message, url, line, col, error) { … };
```
- `message` <sub>(문자열)</sub>
  - 에러 상세 정보
- `url` <sub>(문자열)</sub>
  - 에러 스크립트 url
- `line` · `col` <sub>(숫자)</sub>
  - 에러 위치 줄 · 열
- `error`
  - 에러 객체
```html
<script>
  window.onerror = function(message, url, line, col, error) {
    `${message}\n At ${line}:${col} of ${url}`;
  };

  function readData() {
    badFunc(); // 에러 (미정의 함수)
  }

  readData(); // window.onerror 실행
</script>
```

##### 주요 용도
- 중단된 스크립트 복구 X <sub>(사실상 불가능)</sub>
- 개발자 알림 <sub>(에러 메시지 전송)</sub>

##### 에러 로깅 관련 상용 서비스 <sub>(`window.onerror` 대안)</sub>
- https://errorception.com
- http://www.muscula.com
- 기타 등등

#### 상용 서비스 동작 과정

##### 1. 서비스 가입
- JS 파일 · 스크립트 url 수신 후
  - 페이지 내 삽입

##### 2. JS 파일 · 스크립트 url 동작
- `window.onerror` <sub>(커스텀 함수)</sub> 설정

##### 3. 에러 시 커스텀 함수 동작
- 에러 내용 네트워크 요청 전송 <sub>(→ 서비스)</sub>

##### 4. 서비스 사이트 로그인
- 에러 내역 확인

<br />

요약
====

##### `try…catch`
- 런타임 에러 처리
- `try{…}` <sub>(블록)</sub>
  - 코드 실행
- `catch(…){…}` <sub>(블록)</sub>
  - 에러 처리

##### 주요 구성
```javascript
try {
  …코드 실행…
} catch(e) { // 에러 객체 인수
  …에러 처리…
} finally {  // try…catch 종료 후 항상 실행 (결과 무관)
  …작업 마무리…
}
```
- `try…catch`
- `try…catch…finally`
- `try…finally`

##### 에러 객체 내 프로퍼티
- `name` <sub>(문자열)</sub>
  - 에러명 <sub>(에러 객체 생성자명)</sub>
- `message` <sub>(문자열)</sub>
  - 에러 상세 정보
- `stack` <sub>(非표준 · 대다수 호스트 환경 지원)</sub>
  - 에러 발생 순간 스택

##### `catch` <sub>(문)</sub> 인수 <sub>(에러 객체)</sub> 생략 가능
- `catch(e){…}` → `catch{…}`
- 에러 상세 정보 불필요 시 생략

##### `throw` <sub>(연산자)</sub>
- 에러 직접 생성
- 모든 값 전달 가능 <sub>(인수)</sub>
  - 보통 에러 객체 전달
    - `Error` <sub>(내장 클래스)</sub> 상속

##### 다시 던지기
- `catch(…){…}` <sub>(블록)</sub> 내 처리 불가능 에러
  - 외부 전파 <sub>(외부 `try…catch` 전달)</sub>

##### '전역' 에러 핸들러 <sub>(`try…catch` X)</sub>
- 미처리 에러 처리
- 대다수 호스트 환경 지원
- ex\) `window.onerror` <sub>(브라우저)</sub>

<br />

## <img src="../../images/commons/icons/circle-check-solid.svg" /> 과제

### `finally` 아니면 코드만?

#### 두 코드 조각 비교

##### a. `try…catch…finally`
```javascript
try {
  …작업…
} catch(e) {
  …에러 처리…
} finally {
  …작업 내역 삭제…
}
```

##### b. `try…catch`
```javascript
try {
  …작업…
} catch(e) {
  …에러 처리…
}

…작업 내역 삭제…
```

##### 현재 상황
- 작업 후 초기화 실행 필요 <sub>(에러 유무 무관)</sub>

##### 참고
- `finally` 이점 예시 제시

<br />

<img src="../../images/commons/icons/circle-answer.svg" />

##### `try…catch` 내 '이탈' 코드 → 함수 행동 변화
- `return` <sub>(문)</sub>
- `throw` <sub>(연산자)</sub>

##### `finally` <sub>(절)</sub> 실행 시점
- `try…catch` 종료 <sub>(제어 흐름 외부 이동 전)</sub>
  - `return` <sub>(문)</sub> 도달
  - `throw` <sub>(연산자)</sub> 도달

##### `return` <sub>(문)</sub>
```javascript
function f() {
  try {
    …코드…
    return "결과"; // ←
  } catch(e) {
    …에러 처리…
  } finally {
    …초기화…
  }
}

f();
```

##### `throw` <sub>(연산자)</sub>
```javascript
function f() {
  try {
    …코드…
    throw new Error("에러"); // ←
  } catch(e) {
    …에러 처리…
    if (에러 처리 불가능 시) {
      throw e; // ←
    }
  } finally {
    …초기화…
  }
}

f();
```

##### 초기화 작업 수행 보장 <sub>(`finally` 절 이점)</sub>
- `try…catch` 종료 후 항상 실행 <sub>(결과 무관)</sub>
- `finally` <sub>(절)</sub> 미사용 시 보장 X
  - 코드 이탈 등
