마이크로태스크
=============

##### 프라미스 핸들러 <sub>(`.then` / `.catch` / `.finally`)</sub>
- 항상 비동기적 실행

##### 프라미스 핸들러 아래 코드
- 핸들러들 실행되기 전 실행
  - (프라미스 즉시 이행되더라도)
```javascript
let promise = Promise.resolve();

promise.then(() => alert("프라미스 성공!"));

alert("코드 종료");

// 메시지 출력 순서
// 1. "코드 종료"
// 2. "프라미스 성공!"
```

### 마이크로태스크 큐

##### 비동기 작업 처리 : 적절한 관리 필요
- ECMA
  - `PromiseJobs` <sub>(내부 큐)</sub>
- V8 엔진
  - 마이크로태스크 큐 <sub>(선호 용어)</sub>

##### 명세서 설명
- 먼저 들어온 작업 : 먼저 실행
  - first-in-first-out <sub>(FIFO)</sub>
- 실행할 것 아무것도 남아있지 않을 때
  - 마이크로태스크 큐 내 작업 실행 시작

#### 요약

##### 어떤 프라미스 준비 완료 시
- 이 프라미스의 핸들러
  - 큐에 들어감
  - 실행 X

##### 현재 코드에서 자유로운 상태 되었을 때
- 엔진 : 큐에서 작업 꺼내 실행
- 위 예시
  - `'코드 종료'` : 먼저 출력되는 이유

![promiseQueue](../../images/11/07/promiseQueue.svg)

- 프라미스 핸들러
  - 항상 내부 큐 통과

##### 여러 개의 핸들러 체인
- 각 핸들러
  - 비동기적 실행

##### 큐 내 핸들러들 실행 시점
1. 현재 코드 완료되고
2. 큐 내 적체된 이전 핸들러 실행 완료 시

##### 위 예시 : '프라미스 성공!' → '코드 종료' (순서 바꾸기)
- `.then` 사용
  - `'코드 종료'` : 큐에 넣기
```javascript
Promise.resolve()
  .then(() => alert("프라미스 성공!"))
  .then(() => alert("코드 종료"));
```

### 처리되지 못한 거부

##### `unhandledrejection` <sub>(이벤트)</sub>
- 미처리 거부된 프라미스
  - 전역 에러 처리

##### '처리되지 못한 거부'
- 마이크로태스크 큐 끝
  - 프라미스 에러 미처리 시 발생

##### 정상적인 경우
- 프라미스 체인
  - `.catch` 추가 <sub>(에러 처리)</sub>
```javascript
let promise = Promise.reject(new Error("프라미스 실패!"));
promise.catch(err => alert('잡았다!'));

// 에러 처리됨
// - 실행 X
window.addEventListener('unhandledrejection', event => alert(event.reason));
```

##### `.catch` 미추가 시
- 마이크로태스크 큐 : 빈 이후
  - `unhandledrejection` <sub>(이벤트)</sub> 트리거

let promise = Promise.reject(new Error("프라미스 실패!"));

// 프라미스 실패!
window.addEventListener('unhandledrejection', event => alert(event.reason));
그런데 만약 아래와 같이 setTimeout을 이용해 에러를 나중에 처리하면 어떤 일이 생길까요?

let promise = Promise.reject(new Error("프라미스 실패!"));
setTimeout(() => promise.catch(err => alert('잡았다!')), 1000);

// Error: 프라미스 실패!
window.addEventListener('unhandledrejection', event => alert(event.reason));
예시를 실행하면 프라미스 실패!가 먼저, 잡았다!가 나중에 출력되는 걸 확인할 수 있습니다.

마이크로태스크 큐에 대해 몰랐다면 "에러를 잡았는데도 왜 unhandledrejection 핸들러가 실행되는 거지?"라는 의문을 가졌을 겁니다.

unhandledrejection은 마이크로태스크 큐에 있는 작업 모두가 완료되었을 때 생성됩니다. 엔진은 프라미스들을 검사하고 이 중 하나라도 ‘거부(rejected)’ 상태이면 unhandledrejection 핸들러를 트리거 하죠. 이로써 앞선 의문이 자연스레 해결되었습니다.

위 예시를 실행하면 setTimeout을 사용해 추가한 .catch 역시 트리거 됩니다. 다만 .catch는 unhandledrejection이 발생한 이후에 트리거 되므로 프라미스 실패!가 출력됩니다.