`Promise` <sub>(객체)</sub> 에러 처리
====

##### `Promise` <sub>(객체)</sub> 거부 시 제어 흐름
- 최근접 에러 처리 핸들러 이동
  - 체이닝 시 에러 처리 용이

##### `catch` 핸들러
- 이전 핸들러 내 에러 <sub>(`Promise` 객체 거부)</sub> 처리
  - 체인 끝 위치 권장
- 동작 정상 수행 시 실행 X
- 문제 발생 시 실행
  - 네트워크 이상
  - 부적절한 JSON 형식
  - 기타 등등

##### `fetch` <sub>(메서드)</sub> → 부재 url 전달
```javascript
fetch('https://no-such-server') // 거부 발생
  .then(response => response.json())

  // 이전 핸들러 내 에러 (Promise 객체 거부) 처리
  .catch(alert);
```

##### 응답 내 부적절한 JSON 형식 에러 처리
```javascript
fetch('/article/promise-chaining/user.json')
  .then(response => response.json())
  .then(user => fetch(`https://api.github.com/users/${user.name}`))
  .then(response => response.json())
  .then(githubUser => new Promise((resolve, reject) => {
    let img = document.createElement('img');
    img.src = githubUser.avatar_url;
    img.className = "promise-avatar-example";

    document.body.append(img);

    setTimeout(() => {
      img.remove();

      resolve(githubUser);
    }, 3000);
  }))

  // 이전 핸들러 내 에러 (Promise 객체 거부) 처리
  .catch(e => (e.message);
```

### 암시적 `try…catch`

##### `Promise` <sub>(객체)</sub> · 핸들러 내 코드 대상 적용
- 에러 시 거부 처리 <sub>(에러 → 거부)</sub>
  - 에러 == 거부된 `Promise` <sub>(객체)</sub>
```javascript
new Promise((resolve, reject) => {
  throw new Error("에러");
}).catch(alert); // Error: 에러

↓↓↓

new Promise((resolve, reject) => {
  reject(new Error("에러"));
}).catch(alert); // Error: 에러
```

##### 핸들러 내 에러 시 제어 흐름
- 최근접 에러 처리 핸들러 이동
```javascript
new Promise((resolve, reject) => {
  resolve("OK");
}).then((result) => {

  // Promise (객체) 거부
  throw  new Error("에러");
//reject(new Error("에러"));

// 이전 핸들러 내 에러 (Promise 객체 거부) 처리
}).catch(alert); // Error: 에러
```

##### 모든 에러 유형 처리 <sub>(`throw` 문 외)</sub>
```javascript
new Promise((resolve, reject) => {
  resolve("OK");
}).then((result) => {
  blabla();// 부재 함수 호출
//reject(new ReferenceError(…));

// 이전 핸들러 내 에러 (Promise 객체 거부) 처리
}).catch(alert); // ReferenceError: blabla is not defined
```

##### `catch` 핸들러 처리 대상
- 명시적인 거부
- 이전 핸들러 내 비정상 에러 <sub>(에러 → 거부)</sub>

### 다시 던지기

##### 체인 끝 `.catch` 핸들러
- `try…catch` 유사 역할
- `.then` 핸들러
  - 원하는 만큼 사용
  - 내 발생하는 모든 에러 처리

##### 일반 `try…catch`
- 에러 분석
- 처리 불가능 판단 시 다시 던짐
  - `Promise` <sub>(객체)</sub> : 유사 동작

##### `Promise` <sub>(객체)</sub> 에러 처리 제어 흐름
- 에러 처리 성공 시
  - → 최근접 `.then` 핸들러
    - 실행 이어짐
- `.catch` 내 `throw` 사용 시
  - → 최근접 에러 핸들러

#### `.catch` 핸들러

##### 에러 처리 성공
```javascript
// 실행 순서
// - .catch 핸들러 → .then 핸들러
new Promise((resolve, reject) => {

  throw new Error("에러");

}).catch(function(error) {

  alert("에러가 잘 처리되었습니다. 정상적으로 실행이 이어집니다.");

}).then(() => alert("다음 핸들러가 실행됩니다."));
```
- `.catch(…){…}` <sub>(블록)</sub> 정상 종료
- 다음 `.then` 핸들러 호출

##### 다른 활용 사례
- 에러 잡은 후 다시 던짐
  - 처리 불가능 에러
```javascript
// 실행 순서
// - .catch 핸들러 → .catch 핸들러
new Promise((resolve, reject) => {

  throw new Error("에러");

// 에러 잡음
}).catch(function(error) {

  if (error instanceof URIError) {

    /* 처리 가능 에러 처리 코드 */

  } else {
    alert("처리할 수 없는 에러");

    // 에러 다시 던지기
    // - 처리 불가능 에러
    throw error;
  }

}).then(function() {

  /* 코드 미실행 */

  // 실행 흐름
  // - 1번째 .catch 핸들러 → 다음 .catch 핸들러
}).catch(error => {

  alert(`알 수 없는 에러가 발생함: ${error}`);
  // 반환 값 X
  // 실행 이어짐

});
```

### 처리되지 못한 거부

##### 에러 처리 불가능 경우
- ex\) 체인 끝에 `.catch` 핸들러 부재
```javascript
new Promise(function() {

  // 부재 함수 호출 (에러)
  noSuchFunction();

}).then(() => {

    // 성공 상태 Promise (객체) 처리 핸들러 (.then)
    // - 1 ~ n개 존재

  }); // 체인 끝에 .catch 핸들러 X
```

##### 에러 발생 시
- `Promise` <sub>(객체)</sub> 상태
  - 거부
- 실행 흐름
  - → 최근접 예외 처리 핸들러
- 예외 처리 핸들러 <sub>(에러 처리 코드)</sub> 부재 시
  - 에러 '갇혀버림'
- 코드 내 미처리 에러 잔존 시
  - 실무 : 끔찍한 일 발생

##### `try…catch` : 일반적인 에러 처리 불가능 시
- 스크립트 중단
- 콘솔 창 메시지 출력

##### 거부된 `Promise` <sub>(객체)</sub> 처리 불가능 시
- 유사 동작 발생

##### JS 엔진 : `Promise` <sub>(객체)</sub> 거부 추적 중
- 미처리 거부된 `Promise` <sub>(객체)</sub> 발견 시
  - 전역 에러 생성

#### 비동시 전역 에러
- 체인 끝에 `.catch` 핸들러 부재 시 발생

##### 브라우저 환경
- `unhandledrejection` <sub>(이벤트)</sub>
  - 콘솔 창 확인 가능
  - 표준 이벤트 <sub>(HTML 명세서 정의)</sub>
```javascript
window.addEventListener('unhandledrejection', function(event) {

  // unhandledrejection (이벤트)
  // - 특수 프로퍼티 2개

  // "[object Promise]"
  // - 에러 생성 Promise (객체)
  alert(event.promise);

  // 미처리 에러 객체
  alert(event.reason); // Error: 에러
});

new Promise(function() {
  throw new Error("에러");
}); // 에러 처리 .catch (핸들러) X
```

##### 에러 발생 · 체인 끝 `.catch` 핸들러 無
- `unhandledrejection` 핸들러 트리거
  - `event` <sub>(객체 · 에러 정보 포함)</sub> 받음
  - 핸들러 내 원하는 작업 수행
- 보통 회복 불가능
- 최선의 방법
  - 사용자에게 문제 상황 알리기
  - 서버에 에러 정보 전송 <sub>(가능 시)</sub>

##### 기타 호스트 환경 <sub>(Node.js 등)</sub>
- 미처리 에러 다루는 다양한 방법 제공

<br />

요약
====

#### `.catch`

##### 모든 `Promise` <sub>(객체)</sub> 내 발생 에러 처리
- `reject()` 호출
- 에러 던지기

##### 에러 처리
- 필요 지점에 정확히 위치
- 방법 알고 있어야 함

##### 핸들러
- 에러 분석
  - 커스텀 에러 클래스 유용
- 알 수 없는 에러 <sub>(프로그래밍 실수 등)</sub>
  - 다시 던지기

##### 에러 발생 시 회복 방법 없는 경우
- `.catch` 미사용 OK

##### 전역 에러 처리 핸들러
- 미처리 에러 추적 후 사용자 · 서버 알림
  - 아무 설명 없는 '그냥 사망' 방지
- ex\) 브라우저 환경
  - `unhandledrejection` <sub>(핸들러)</sub>

<br />

## <img src="../../images/commons/icons/circle-check-solid.svg" /> 과제

### `setTimeout` <sub>(함수)</sub> 내 에러

##### `.catch` 핸들러 트리거 여부 · 이유
```javascript
new Promise(function(resolve, reject) {
  setTimeout(() => {
    throw new Error("에러");
  }, 1000);
}).catch(alert);
```

<br />

<img src="../../images/commons/icons/circle-answer.svg" />

#### `.catch` 핸들러 트리거 X

##### 암시적 `try…catch`
- 함수 코드 감싸고 있음
  - 모든 동기적 에러 처리

##### `setTimeout` <sub>(메서드)</sub> 내 에러 발생 시점
- executor 실행 중 X
- 나중
  - `Promise` <sub>(객체)</sub> : 에러 처리 X
