프라미스와 에러 핸들링
====================

- 프라미스 거부 시 제어 흐름
  - → 가장 가까운 예외 처리 핸들러
- 프라미스 체인
  - 에러 쉽게 처리
  - 실무 아주 유용
- 미존재 주소 → `fetch` <sub>(메서드)</sub> 전달
  - `.catch` 핸들러 : 에러 처리
```javascript
fetch('https://no-such-server.blabla') // 거부
  .then(response => response.json())

  // TypeError: failed to fetch
  // - 출력 내용 다를 수 있음
  .catch(err => alert(err));
```

##### `.catch` 핸들러
- 1번째 핸들러일 필요 X
- 1 ~ n개 `.then` 뒤에 위치 가능

##### 잘못된 응답 JSON 형식 <sub>(사이트 문제 X)</sub>
- 가장 쉬운 에러 처리 방법
  - 체인 끝에 `.catch` 핸들러 추가
```javascript
fetch('/article/promise-chaining/user.json')
  .then(response => response.json())
  .then(user => fetch(`https://api.github.com/users/${user.name}`))
  .then(response => response.json())
  .then(githubUser => new Promise((resolve, reject) => {
    let img = document.createElement('img');
    img.src = githubUser.avatar_url;
    img.className = "promise-avatar-example";
    document.body.append(img);

    setTimeout(() => {
      img.remove();
      resolve(githubUser);
    }, 3000);
  }))
  .catch(error => alert(error.message));
```
- 정상적인 경우
  - `.catch` 핸들러 트리거 X
- 문제 발생
  - 네트워크 문제
  - 잘못된 JSON 형식
  - 기타 등등
- 이전 프라미스 중 하나라도 거부 시
  - `.catch` 핸들러 : 에러 잡음

### 암시적 `try…catch`

##### executor · 핸들러 코드 주위
- '보이지 않는 <sub>(암시적)</sub>' `try…catch` 존재
  - 예외 발생 시 잡음
  - `reject` <sub>(프라미스)</sub> 처럼 처리
```javascript
new Promise((resolve, reject) => {
  throw new Error("에러 발생!");
}).catch(alert); // Error: 에러 발생!

↓↓↓ // 동일 동작

new Promise((resolve, reject) => {
  reject(new Error("에러 발생!"));
}).catch(alert); // Error: 에러 발생!
```

##### executor
- 스스로 에러 잡음
- 에러 발생 시
  - 거부된 프라미스 <sub>(상태 변경)</sub>

##### 핸들러
- `.then` 핸들러 내 에러 던질 시 <sub>(`throw`)</sub>
  - 이 자체 == 거부된 프라미스
- 제어 흐름
  - → 가장 가까운 에러 핸들러
```javascript
new Promise((resolve, reject) => {
  resolve("OK");
}).then((result) => {

  // 프라미스 거부됨
  throw new Error("에러 발생!");

  // Error: 에러 발생!
}).catch(alert);
```

##### 암시적 `try…catch`
- 모든 종류 에러 처리
```javascript
new Promise((resolve, reject) => {
  resolve("OK");
}).then((result) => {

  // 존재하지 않는 함수 호출
  blabla();

  // ReferenceError: blabla is not defined
}).catch(alert);
```

##### `.catch` 핸들러
- 명시적인 거부 잡음
- 핸들러 위쪽 비정상 에러 잡음

### 다시 던지기

##### 체인 끝 `.catch` 핸들러
- `try…catch` 유사 역할
- `.then` 핸들러
  - 원하는 만큼 사용
  - 내 발생하는 모든 에러 처리

##### 일반 `try…catch`
- 에러 분석
- 처리 불가 판단 시 다시 던짐
  - 프라미스 : 유사 동작

##### 프라미스 에러 처리 제어 흐름
- 에러 처리 성공 시
  - → 가장 가까운 `.then` 핸들러
    - 실행 이어짐
- `.catch` 내 `throw` 사용 시
  - → 가장 가까운 에러 핸들러

#### `.catch` 핸들러

##### 에러 처리 성공
```javascript
// 실행 순서
// - .catch 핸들러 → .then 핸들러
new Promise((resolve, reject) => {

  throw new Error("에러 발생!");

}).catch(function(error) {

  alert("에러가 잘 처리되었습니다. 정상적으로 실행이 이어집니다.");

}).then(() => alert("다음 핸들러가 실행됩니다."));
```
- `.catch` 블록 정상 종료
- 다음 `.then` 핸들러 호출

##### 다른 활용 사례
- 에러 잡은 후 다시 던짐
  - 처리 불가 에러
```javascript
// 실행 순서
// - .catch 핸들러 → .catch 핸들러
new Promise((resolve, reject) => {

  throw new Error("에러 발생!");

// 에러 잡음
}).catch(function(error) {

  if (error instanceof URIError) {

    /* 처리 가능 에러 처리 코드 */

  } else {
    alert("처리할 수 없는 에러");

    // 에러 다시 던지기
    // - 처리 불가 에러
    throw error;
  }

}).then(function() {

  /* 코드 실행 X */

  // 실행 흐름
  // - 1번째 .catch 핸들러 → 다음 .catch 핸들러
}).catch(error => {

  alert(`알 수 없는 에러가 발생함: ${error}`);
  // 반환값 X
  // 실행 이어짐

});
```

### 처리되지 못한 거부

##### 에러 처리 불가능 경우
- ex&#41; 체인 끝에 `.catch` 핸들러 부재
```javascript
new Promise(function() {

  // 미존재 함수 호출
  // - 에러 발생
  noSuchFunction();

}).then(() => {

    // 성공 상태 프라미스 처리 핸들러 (.then)
    // - 1 ~ n개 존재

  }); // 체인 끝에 .catch 핸들러 X
```

##### 에러 발생 시
- 프라미스 상태
  - 거부 상태
- 실행 흐름
  - → 가장 가까운 예외 처리 핸들러
- 예외 처리 핸들러 <sub>(에러 처리 코드)</sub> 부재 시 
  - 에러 '갇혀버림'
- 코드 내 미처리 에러 잔존 시
  - 실무 : 끔찍한 일 발생

##### `try…catch` : 일반적인 에러 처리 불가능 시
- 스크립트 중단
- 콘솔 창 메시지 출력

##### 거부된 프라미스 처리 불가능 시
- 유사 동작 발생

##### JS 엔진 : 미처리 거부된 프라미스 발견 시 <sub>(프라미스 거부 추적 중)</sub>
  - 미처리 거부된 프라미스 발견 시
    - 전역 에러 생성
- `unhandledrejection` <sub>(이벤트)</sub> 처리
  - 콘솔창 확인 <sub>(브라우저 환경)</sub>
  - 표준 이벤트 <sub>(HTML 명세서 정의)</sub>
```javascript
window.addEventListener('unhandledrejection', function(event) {

  // unhandledrejection (이벤트)
  // - 특수 프로퍼티 2개
  alert(event.promise); // [object Promise]
                        // - 에러 생성 프라미스
  alert(event.reason);  // Error: 에러 발생!
                        // - 처리 못한 에러 객체
});

new Promise(function() {
  throw new Error("에러 발생!");
}); // 에러 처리 .catch (핸들러) X
```

##### 브라우저 환경
- 에러 발생 시 `.catch` X
  - `unhandledrejection` <sub>(핸들러)</sub> 트리거
    - `event` <sub>(객체 with 에러 정보)</sub> 받음
    - 핸들러 내 원하는 작업 수행
- 대개 이런 에러 회복 X
- 최선의 방법
  - 사용자에게 문제 상황 알리기
  - 서버에 에러 정보 전송 <sub>(가능 시)</sub>
- 기타 호스트 환경 <sub>(Node.js 등)</sub>
  - 미처리 에러 다루는 방법
    - 여러 가지 제공

### <img class="icon" src="../../images/commons/icons/circle-check-solid.svg" /> 과제
<hr />

### setTimeout 내 에러
- `.catch` 트리거 발생 여부?
```javascript
new Promise(function(resolve, reject) {
  setTimeout(() => {
    throw new Error("에러 발생!");
  }, 1000);
}).catch(alert);
```
<img class="icon" src="../../images/commons/icons/circle-answer.svg" />
<br />

- `.catch` 트리거 X
```javascript
new Promise(function(resolve, reject) {
  setTimeout(() => {
    throw new Error("에러 발생!");
  }, 1000);
}).catch(alert);
```

##### '암시적' `try…catch`
- 함수 코드 감싸고 있음
  - 모든 동기적 에러 처리

##### 과제 에러 발생 시점
- `executor` <sub>(실행자 · 실행 함수)</sub> 실행 중 X
- 나중
  - 프라미스 에러 처리 X
